

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "AboutPage.xaml.h"




void ::Wikipedia::AboutPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///AboutPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///AboutPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'LayoutRoot'
    LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"LayoutRoot"));
    // Get the Grid named 'ContentRoot'
    ContentRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ContentRoot"));
    // Get the TextBlock named 'Copyright'
    Copyright = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Copyright"));
    // Get the TextBlock named 'WikipediaContent'
    WikipediaContent = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"WikipediaContent"));
    // Get the TextBlock named 'Feedback'
    Feedback = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Feedback"));
    // Get the Hyperlink named 'email'
    email = safe_cast<::Windows::UI::Xaml::Documents::Hyperlink^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"email"));
    // Get the Run named 'ByUsingThis'
    ByUsingThis = safe_cast<::Windows::UI::Xaml::Documents::Run^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ByUsingThis"));
    // Get the Run named 'and'
    and = safe_cast<::Windows::UI::Xaml::Documents::Run^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"and"));
    // Get the Run named 'PrivacyPolicy'
    PrivacyPolicy = safe_cast<::Windows::UI::Xaml::Documents::Run^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"PrivacyPolicy"));
    // Get the Run named 'TermsOfUse'
    TermsOfUse = safe_cast<::Windows::UI::Xaml::Documents::Run^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TermsOfUse"));
    // Get the Run named 'CreativeCommons'
    CreativeCommons = safe_cast<::Windows::UI::Xaml::Documents::Run^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CreativeCommons"));
    // Get the TextBlock named 'AppTitle'
    AppTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"AppTitle"));
    // Get the TextBlock named 'AboutTitle'
    AboutTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"AboutTitle"));
}

void ::Wikipedia::AboutPage::Connect(int connectionId, Platform::Object^ target)
{
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

