

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBox;
                ref class TextBlock;
                ref class AppBarButton;
            }
        }
    }
}

namespace Wikipedia
{
    partial ref class EditPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ ContentRoot;
        private: ::Windows::UI::Xaml::Controls::TextBox^ EditBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Title;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ CancelAppBarButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ PreviewAppBarButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ SaveAppBarButton;
    };
}

