

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "HistoryResultUserControl.xaml.h"




void ::Wikipedia::HistoryResultUserControl::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///HistoryResultUserControl.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///HistoryResultUserControl.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the TextBlock named 'userTextBlock'
    userTextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"userTextBlock"));
    // Get the TextBlock named 'timestampTextBlock'
    timestampTextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"timestampTextBlock"));
    // Get the TextBlock named 'commentTextBlock'
    commentTextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"commentTextBlock"));
}

void ::Wikipedia::HistoryResultUserControl::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerPressed +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Wikipedia::HistoryResultUserControl::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&HistoryResultUserControl::HistoryResultUserControl_Clicked);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

