

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "PreviewPage.xaml.h"




void ::Wikipedia::PreviewPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///PreviewPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///PreviewPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the WebView named 'WebViewControl'
    WebViewControl = safe_cast<::Windows::UI::Xaml::Controls::WebView^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"WebViewControl"));
    // Get the AppBarButton named 'EditAppBarButton'
    EditAppBarButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"EditAppBarButton"));
    // Get the AppBarButton named 'CancelAppBarButton'
    CancelAppBarButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CancelAppBarButton"));
    // Get the AppBarButton named 'SaveAppBarButton'
    SaveAppBarButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SaveAppBarButton"));
}

void ::Wikipedia::PreviewPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::WebView^>(target))->ContentLoading +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewContentLoadingEventArgs^>(this, (void (::Wikipedia::PreviewPage::*)(Windows::UI::Xaml::Controls::WebView^, Windows::UI::Xaml::Controls::WebViewContentLoadingEventArgs^))&PreviewPage::WebViewControl_ContentLoading);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Wikipedia::PreviewPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&PreviewPage::EditAppBarButton_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Wikipedia::PreviewPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&PreviewPage::CancelAppBarButton_Click);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Wikipedia::PreviewPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&PreviewPage::SaveAppBarButton_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

