

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "SavePage.xaml.h"




void ::Wikipedia::SavePage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///SavePage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///SavePage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'ContentRoot'
    ContentRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ContentRoot"));
    // Get the Button named 'SaveButton'
    SaveButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SaveButton"));
    // Get the TextBox named 'SummaryBox'
    SummaryBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SummaryBox"));
    // Get the CheckBox named 'MinorEditBox'
    MinorEditBox = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"MinorEditBox"));
    // Get the StackPanel named 'Captcha'
    Captcha = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Captcha"));
    // Get the TextBox named 'CAPTCHABox'
    CAPTCHABox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CAPTCHABox"));
    // Get the Button named 'SubmitButton'
    SubmitButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SubmitButton"));
    // Get the Run named 'TextA'
    TextA = safe_cast<::Windows::UI::Xaml::Documents::Run^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TextA"));
    // Get the Run named 'Summary'
    Summary = safe_cast<::Windows::UI::Xaml::Documents::Run^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Summary"));
    // Get the TextBlock named 'SavingChangesTo'
    SavingChangesTo = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SavingChangesTo"));
}

void ::Wikipedia::SavePage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Wikipedia::SavePage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&SavePage::SaveButton_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Wikipedia::SavePage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&SavePage::SubmitButton_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

