

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "SearchContentDialog.xaml.h"




void ::Wikipedia::SearchContentDialog::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///SearchContentDialog.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///SearchContentDialog.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the TextBox named 'SearchBox'
    SearchBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SearchBox"));
    // Get the StackPanel named 'ResultsPanel'
    ResultsPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ResultsPanel"));
    // Get the Button named 'ContinueButton'
    ContinueButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ContinueButton"));
}

void ::Wikipedia::SearchContentDialog::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(target))->TextChanged +=
            ref new ::Windows::UI::Xaml::Controls::TextChangedEventHandler(this, (void (::Wikipedia::SearchContentDialog::*)(Platform::Object^, Windows::UI::Xaml::Controls::TextChangedEventArgs^))&SearchContentDialog::SearchBox_TextChanged);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Wikipedia::SearchContentDialog::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&SearchContentDialog::MoreSearchResults);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

